name: Obfuscate JS Files

on:
  push:
    branches: [main]

jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Terser
        run: npm install -g terser

      - name: Obfuscate JS files
        run: |
          mkdir -p dist
          cp -r assets dist/
          find dist/assets/js -name "*.js" -type f -exec sh -c 'terser "$0" -c -m -o "$0.min.js" && mv "$0.min.js" "$0"' {} \;

      - name: Copy other files
        run: |
          cp index.html dist/ 2>/dev/null || :
          # 필요한 다른 파일들도 여기에 복사 명령 추가

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
