name: Obfuscate JS Files

on:
  push:
    branches: [main]

jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Terser
        run: npm install -g terser

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy files to dist
        run: |
          cp -r assets dist/
          cp index.html dist/ || true
          cp -r images dist/ || true
          cp -r css dist/ || true

      - name: Debug - Show files
        run: find dist -type f -name "*.js" | sort

      - name: Obfuscate JS files
        run: |
          find dist -name "*.js" -type f -exec sh -c 'echo "Obfuscating $0"; terser "$0" --compress --mangle --output "$0.min" && mv "$0.min" "$0"' {} \;

      - name: Debug - Show obfuscated files
        run: |
          echo "===== VERIFYING OBFUSCATION ====="
          find dist -name "*.js" -type f -exec sh -c 'echo "$0"; head -n 3 "$0"' {} \;
          echo "================================="

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
