name: Obfuscate JS Files

on:
  push:
    branches: [main]

jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Terser
        run: npm install -g terser

      - name: Obfuscate JS files
        run: |
          mkdir -p dist
          cp -r assets dist/
          find dist/assets/js -name "*.js" -type f -exec sh -c 'terser "$0" --compress --mangle --output "$0.min" && cat "$0.min" > "$0" && rm "$0.min"' {} \;

      - name: Verify obfuscation
        run: |
          echo "===== VERIFYING OBFUSCATION ====="
          ls -la dist/assets/js/
          head -n 5 dist/assets/js/*.js
          echo "================================="

      - name: Copy other files
        run: |
          cp index.html dist/ || true
          cp -r images dist/ || true
          cp -r css dist/ || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
