name: Obfuscate JS Files

on:
  push:
    branches: [main]

jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Show repository structure
        run: |
          echo "===== REPOSITORY STRUCTURE ====="
          find . -type f | grep -E '\.(js|html)$' | sort
          echo "================================"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install JavaScript-Obfuscator
        run: npm install -g javascript-obfuscator uglify-js

      - name: Create clean dist directory
        run: |
          rm -rf dist
          mkdir -p dist

      - name: Copy all files to dist
        run: |
          cp -r * dist/ || true
          find dist -type d -name ".git*" -exec rm -rf {} + || true

      - name: Create comparison samples (before obfuscation)
        run: |
          mkdir -p samples
          find dist -name "*.js" -type f | head -3 | xargs -I{} cp {} samples/
          ls -la samples/

      - name: Double obfuscation approach
        run: |
          find dist -name "*.js" -type f -print | while read jsfile; do
            echo "Processing: $jsfile"
            # Step 1: First obfuscation with javascript-obfuscator
            javascript-obfuscator "$jsfile" --output "$jsfile.temp" \
              --compact true \
              --control-flow-flattening true \
              --dead-code-injection true \
              --string-array true \
              --self-defending true
              
            # Step 2: Second pass with UglifyJS for extra minification  
            uglifyjs "$jsfile.temp" --compress --mangle --output "$jsfile"
            
            # Remove temp file
            rm "$jsfile.temp"
            
            # Show file size difference
            original_size=$(wc -c < samples/$(basename "$jsfile") 2>/dev/null || echo "N/A")
            new_size=$(wc -c < "$jsfile")
            echo "Size: $original_size → $new_size bytes"
          done

      - name: Compare before and after (sample)
        run: |
          echo "===== BEFORE OBFUSCATION ====="
          head -10 samples/*.js || true
          echo "===== AFTER OBFUSCATION ====="
          find dist -name "*.js" -type f | head -3 | xargs -I{} head -10 {}
          echo "============================="

      - name: Add verification marker to HTML files
        run: |
          find dist -name "*.html" -type f -exec sh -c '
            echo "Adding verification marker to $0"
            MARKER="<!-- JS files obfuscated on: $(date) -->"
            sed -i "1s|^|$MARKER\n|" "$0"
            
            # Add cache busting to all script tags
            TIMESTAMP=$(date +%s)
            sed -i "s/\.js/\.js?v=$TIMESTAMP/g" "$0"
          ' {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
